name: Deploy AWS

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build with Maven
        run: mvn -q -DskipTests package

      - name: Login to Docker Hub (your account)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projeto-software-exercicio:${{ steps.vars.outputs.TAG }}

      - name: Deploy on EC2 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_TEST }}
          username: ubuntu
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            set -e
            docker network inspect rede >/dev/null 2>&1 || docker network create -d bridge rede
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/projeto-software-exercicio:${{ steps.vars.outputs.TAG }}
            (docker rm -f pessoas-app || true)
            docker run -d --name pessoas-app \
              --network=rede \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/projeto-software-exercicio:${{ steps.vars.outputs.TAG }}
